trigger:
  branches:
    include:
      - main

# Define the stages of the pipeline
stages:

  # Build stage
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: BuildJob
        displayName: 'Build Job'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: NodeTaskRunnerInstaller@0
            inputs:
              nodeVersion: '16'
          - script: |
              echo "Installing dependencies"
              npm install
            displayName: 'Install Dependencies'
          - script: |
              echo "Testing the project"
              npm test
            displayName: 'Code Coverage'
          - script: |
              echo "Running coverage on the project"
              npm run coverage
            displayName: 'Code Coverage'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "$(System.DefaultWorkingDirectory)/test-results.xml"
              ArtifactName: "_drop"
              publishLocation: "Container"
          # - publish: $(Build.ArtifactStagingDirectory)
          #   artifact: 'drop'
          #   displayName: 'Publish Artifact'

  # Test stage (conditional on successful build)
  # - stage: Test
  #   displayName: 'Test Stage'
  #   dependsOn: Build
  #   condition: succeeded()
  #   jobs:
  #     - job: TestJob
  #       displayName: 'Run Tests'
  #       pool:
  #         vmImage: 'ubuntu-latest'
  #       steps:
  #         - script: |
  #             echo "Running tests"
  #             npm test
  #           displayName: 'Run Unit Tests'

  # # Deploy stage (conditional on successful tests)
  # - stage: Deploy
  #   displayName: 'Deploy Stage'
  #   dependsOn: Test
  #   condition: succeeded()
  #   jobs:
  #     - deployment: DeployApp
